name: Build and Deploy Weather App

on:
  push:
    branches:
      - main  # Only run on push to main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          echo "Creating binary..."
          pyinstaller --onefile weather.py
          echo "Binary created at dist/weather"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-build
          path: dist/weather

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-build
          path: dist/

      - name: Prepare SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to $USER@$HOST:/home/Result/"
          scp -o StrictHostKeyChecking=no -i deploy_key.pem dist/weather $USER@$HOST:/home/Result/
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST 'systemctl restart weather-app'

