name: Build and Deploy Weather App

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: self-hosted  # Uses your RHEL self-hosted runner . it is being used now what to do
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build binary
        run: |
          echo "Creating binary..."
          pyinstaller --onefile weather.py
          echo "Binary created at dist/weather"

      - name: Upload dev build artifact
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v2
        with:
          name: weather-dev-build
          path: dist/weather

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --onefile weather.py
          echo "Binary created at dist/weather"

      - name: Prepare SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to $USER@$HOST:/home/Result/"
          scp -o StrictHostKeyChecking=no -i deploy_key.pem dist/weather $USER@$HOST:/home/Result/
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST 'systemctl restart weather-app'

