name: Build and Deploy Weather App

# Trigger the workflow when code is pushed to `dev` or `main` branches
on:
  push:
    branches:
      - dev
      - main

jobs:
  # Build job for both dev and main branches
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if any)
        run: |
          # Add your test commands here, e.g., pytest
          echo "Running tests..."

  # Deployment job for `main` branch only
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to $USER@$HOST:/home/Result/"
          # Copy the binary to /home/Result/  now
          scp -o StrictHostKeyChecking=no -i deploy_key.pem weather.py $USER@$HOST:/home/Result/
          # Restart the weather-app service on the server
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST 'systemctl restart weather-app'

