name: Build and Deploy Weather App

on:
  push:
    branches:
      - main  # Only trigger on main branch

jobs:
  build:
    runs-on: self-hosted  # Your RHEL self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use a specific valid Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          echo "Creating binary..."
          pyinstaller --onefile weather.py
          echo "Binary created at dist/weather"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # Use v4 (v2 is deprecated)
        with:
          name: weather-build
          path: dist/weather

  deploy:
    needs: build
    runs-on: self-hosted  # Same runner used

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-build
          path: dist/

      - name: Deploy binary to local path
        run: |
          echo "Copying binary to /home/Result/"
          cp dist/weather /home/Result/weather
          chmod +x /home/Result/weather
          echo "Restarting weather-app service..."
          sudo systemctl restart weather-app

