name: Build and Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DEPLOY_DIR: /home/Result

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Ensure deployment directory exists
        run: mkdir -p $DEPLOY_DIR

      - name: Deploy artifact locally
        run: |
          cp target/weather-app.jar $DEPLOY_DIR/weather-app-${{ github.run_number }}.jar

      - name: Notify
        run: echo "Deployed weather-app-${{ github.run_number }}.jar to $DEPLOY_DIR"

